### ISSUE TITLE
[Shakemap Grid Importer] Error on converting grid.xm

### ISSUE THREAD

**Issue by ismailsunni** [north-road/inasafe#33]
### Problem
- Using this file
[20180612140530-initial-grid.xml.zip](https://github.com/north-road/inasafe/files/2093543/20180612140530-initial-grid.xml.zip)
- Run conversion (no set any options)
- I got this error

```
AttributeError: type object 'QgsColorRampShader' has no attribute 'INTERPOLATED' 
Traceback (most recent call last):
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/gui/tools/shake_grid/shakemap_converter_dialog.py", line 278, in accept
    mmi_ramp_roman(self.output_layer)
  File "/Users/ismailsunni/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/inasafe/safe/utilities/styling.py", line 66, in mmi_ramp_roman
    ramp_shader.setColorRampType(QgsColorRampShader.INTERPOLATED)
AttributeError: type object 'QgsColorRampShader' has no attribute 'INTERPOLATED'
```

It works fine in QGIS 2.18 and InaSAFE 4.4

**Comment by nyalldawson** [comment]
Fixed by https://github.com/inasafe/inasafe/pull/5000/commits/4e527b3d15f94198dffb687fe12ce0c869cd9264

**Comment by ismailsunni** [comment]
Checked.
